firstName = input("input users firstName:")
lastName = input("input users lastName:")
state = input("input users state:")
year = input("input users year:")
print(firstName +" "+ lastName +" "+ state +" "+ year)